name: Build & Publish to GCP
on:
  pull_request:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GCR_PROJECT }}
  APPLICATION_CREDENTIALS: ${{ secrets.GCR_JSON_KEY }}
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v2
        with:
          always-auth: true
          node-version: '20.x'
          registry-url: https://npm.pkg.github.com
          scope: '@freestarcapital'
      - run: npm install
      - run: gulp build --modules=modules.json
